config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'relationships/create'
  get 'relationships/destroy'
  get 'likes/create'
  get 'likes/destroy'
  get 'replies/new'
  get 'replies/create'
  get 'replies/destroy'
  get 'users/index'
  get 'users/show'
  get 'main/home'
  get 'main/about'
  get 'main/contact'
  get 'main/terms'
  get 'main/privacy'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
    resources :replies, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i[create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'profiles#index'
end

app/models/profile.rb
class Profile < ApplicationRecord
    has_one_attached :picture
    has_one_attached :cv_upload
    has_one_attached :certificate
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:picture, :personal_statement, :first_name, :last_name, 
        :email_address, :phone_number, :nationality, :gender, :date_of_birth, :designation, :school, :highest_qualification,
        :institution, :job_title, :start_date, :end_date, :reference_name, :reference_email,
        :institution2, :job_title2, :start_date2, :end_date2, :reference_name2, :reference_email2,
        :institution3, :job_title3, :start_date3, :end_date3, :reference_name3, :reference_email3, :cv_upload, :certificate)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class="w-100">
  <%= form_with(model: @profile, local: true) do |f| %>
  <div class="row align-items-start py-3 border-bottom">
    <div class="col-12 col-md-6 pl-sm-4 pl-2">
      <b>Profile Photo</b>
      <% if @profile.picture.attached? %> <%= image_tag @profile.picture, class: "rounded-circle d-block", width: "100px", height: "100px" %> <% else %>
      <img class="rounded-circle d-block" src="https://images.pexels.com/photos/1037995/pexels-photo-1037995.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" width="100px" height="100px" alt="" />
      <% end %>
      <p>Accepted file type .png. Less than 1MB</p>
      <%= f.file_field :picture, class: "btn" %>
    </div>
    <div class="col-12 col-md-6 align-items-start pb-3">
      <%= f.label :personal_statement, class: "flabel" %> <%= f.text_area :personal_statement, rows: "5", class: "bg-light form-control" %>
    </div>
  </div>

  <div class="container">
    <div class="row py-2">
      <div class="col-12 col-md-6">
        <%= f.label :first_name, class: "flabel" %> <%= f.text_field :first_name, class: "bg-light form-control", placeholder: "Steve" %>
      </div>
      <div class="col-12 col-md-6 pt-md-0 pt-3">
        <%= f.label :last_name, class: "flabel" %> <%= f.text_field :last_name, class: "bg-light form-control", placeholder: "Smith" %>
      </div>
    </div>
    <div class="row py-2">
      <div class="col-12 col-md-6">
        <%= f.label :email_address, class: "flabel" %> <%= f.email_field :email_address, class: "bg-light form-control", placeholder: "steve_@email.com" %>
      </div>
      <div class="col-12 col-md-6 pt-md-0 pt-3">
        <%= f.label :phone_number, class: "flabel" %> <%= f.telephone_field :phone_number, class: "bg-light form-control", placeholder: "+971........." %>
      </div>
    </div>
    <div class="row py-2">
      <div class="col-12 col-md-6">
        <%= f.label :nationality, class: "flabel" %> <%= f.text_field :nationality, class: "bg-light form-control", placeholder: "United Arab Emirates" %>
      </div>
      <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
        <%= f.label :gender, class: "flabel" %> <%= f.text_field :gender, class: "bg-light form-control", placeholder: "Gender" %>
      </div>
    </div>
    <div class="row py-2">
      <div class="col-12 col-md-6">
        <%= f.label :date_of_birth, class: "flabel" %> <%= f.date_field :date_of_birth, class: "bg-light form-control", placeholder: "DD-MM-YYYY" %>
      </div>
      <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
        <%= f.label :designation, class: "flabel" %> <%= f.text_field :designation, class: "bg-light form-control", placeholder: "Designation" %>
      </div>
    </div>
    <hr />
    <div class="text-left">
      <h3>Academic Profile</h3>
    </div>
    <div class="row py-2">
      <div class="col-12 col-md-6">
        <%= f.label :school, class: "flabel" %> <%= f.text_field :school, class: "bg-light form-control", placeholder: "School name" %>
      </div>
      <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
        <%= f.label :highest_qualification, class: "flabel" %> <%= f.text_field :highest_qualification, class: "bg-light form-control", placeholder: "BEd in Psychology" %>
      </div>
    </div>
    <hr />
    <div>
      <h3>Work Experience</h3>
    </div>
    <div class="experience">
      <div class="row py-2">
        <div class="col-12 col-md-6">
          <%= f.label :institution, class: "flabel" %> <%= f.text_field :institution, class: "bg-light form-control", placeholder: "Institution" %>
        </div>
        <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
          <%= f.label :job_title, class: "flabel" %> <%= f.text_field :job_title, class: "bg-light form-control", placeholder: "Position" %>
        </div>
      </div>
      <div class="row py-2">
        <div class="col-12 col-md-6">
          <%= f.label :start_date, class: "flabel" %> <%= f.date_field :start_date, class: "bg-light form-control", placeholder: "DD-MM-YYYY" %>
        </div>
        <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
          <%= f.label :end_date, class: "flabel" %> <%= f.date_field :end_date, class: "bg-light form-control", placeholder: "DD-MM-YYYY" %>
        </div>
      </div>
      <div class="row py-2">
        <div class="col-12 col-md-6">
          <%= f.label :reference_name, class: "flabel" %> <%= f.text_field :reference_name, class: "bg-light form-control", placeholder: "Reference Name" %>
        </div>
        <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
          <%= f.label :reference_email, class: "flabel" %> <%= f.email_field :reference_email, class: "bg-light form-control", placeholder: "steve_@email.com" %>
        </div>
      </div>
    </div>
    <div class="experience d-none">
      <div class="row py-2">
        <div class="col-12 col-md-6">
          <%= f.label :institution, class: "flabel" %> <%= f.text_field :institution2, class: "bg-light form-control", placeholder: "Institution" %>
        </div>
        <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
          <%= f.label :job_title, class: "flabel" %> <%= f.text_field :job_title2, class: "bg-light form-control", placeholder: "Position" %>
        </div>
      </div>
      <div class="row py-2">
        <div class="col-12 col-md-6">
          <%= f.label :start_date, class: "flabel" %> <%= f.date_field :start_date2, class: "bg-light form-control", placeholder: "DD-MM-YYYY" %>
        </div>
        <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
          <%= f.label :end_date, class: "flabel" %> <%= f.date_field :end_date2, class: "bg-light form-control", placeholder: "DD-MM-YYYY" %>
        </div>
      </div>
      <div class="row py-2">
        <div class="col-12 col-md-6">
          <%= f.label :reference_name, class: "flabel" %> <%= f.text_field :reference_name2, class: "bg-light form-control", placeholder: "Reference Name" %>
        </div>
        <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
          <%= f.label :reference_email, class: "flabel" %> <%= f.email_field :reference_email2, class: "bg-light form-control", placeholder: "steve_@email.com" %>
        </div>
      </div>
    </div>
    <div class="experience d-none">
      <div class="row py-2">
        <div class="col-12 col-md-6">
          <%= f.label :institution, class: "flabel" %> <%= f.text_field :institution3, class: "bg-light form-control", placeholder: "Institution" %>
        </div>
        <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
          <%= f.label :job_title, class: "flabel" %> <%= f.text_field :job_title3, class: "bg-light form-control", placeholder: "Position" %>
        </div>
      </div>
      <div class="row py-2">
        <div class="col-12 col-md-6">
          <%= f.label :start_date, class: "flabel" %> <%= f.date_field :start_date3, class: "bg-light form-control", placeholder: "DD-MM-YYYY" %>
        </div>
        <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
          <%= f.label :end_date, class: "flabel" %> <%= f.date_field :end_date3, class: "bg-light form-control", placeholder: "DD-MM-YYYY" %>
        </div>
      </div>
      <div class="row py-2">
        <div class="col-12 col-md-6">
          <%= f.label :reference_name, class: "flabel" %> <%= f.text_field :reference_name3, class: "bg-light form-control", placeholder: "Reference Name" %>
        </div>
        <div class="col-12 col-md-6 pt-md-0 pt-3" id="lang">
          <%= f.label :reference_email, class: "flabel" %> <%= f.email_field :reference_email3, class: "bg-light form-control", placeholder: "steve_@email.com" %>
        </div>
      </div>
    </div>
    <div class="text-right">
      <a class="btn btn-primary" id="add-experience" href="#" role="button">Add Experience</a>
      <div>
        <hr />
        <div class="row d-flex py-3">
          <div class="col-12 col-md-6 text-left">
            <h5 class="text-left">CV</h5>
            <%= f.file_field :cv_upload, class: "btn ml-n3" %>
          </div>
          <div class="col-12 col-md-6 text-left">
            <h5>Certificate/Diploma</h5>
            <%= f.file_field :certificate, class: "btn ml-n3" %>
          </div>
        </div>
        <div class="py-3 pb-4 border-bottom">
          <%= f.submit "Save", class: "btn w-25 btn-primary mr-3" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="py-3 border-bottom">Update Profile</h4>
    <%= render 'form', profile: @profile %> <%= link_to 'Show', @profile %> | <%= link_to 'Back', profiles_path %>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="container">
  <div class="row">
    <aside class="col-12 col-md-3">
      <%= side_panel_on %>
    </aside>
    <section class="col-12 col-md-9">
      <h3>Find your LSA</h3>
      <div class="">
        <% @profiles.each do |profile| %>
        <article class="d-flex">
          <div class="thumbnail">
            <figure class="">
              <% if profile.picture.attached? %> <%= image_tag profile.picture, class: "rounded-circle d-block", width: "50px", height: "50px" %> <% else %>
              <img class="rounded-circle d-block" src="https://images.pexels.com/photos/1037995/pexels-photo-1037995.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" width="100px" height="100px" alt="" />
              <% end %>
            </figure>
          </div>
          <div class="ml-2">
            <h4 class="bg-secondary rounded">Learning Support Assistant</h4>
            <div class="">
              Full name: <%= link_to profile.first_name + " " + profile.last_name, profile_path(profile), class: 'menu-link' %>
            </div>
            <div class="">
              Nationality: <%= profile.nationality %>
            </div>
            <div class="">
              Gender: <%= profile.gender %>
            </div>
            <div class="">
              <h5>Personal Statement</h5>
              <p>
                <%= profile.personal_statement %>
              </p>
            </div>
          </div>
        </article>
        <% end %>
        <div>
          <section></section>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <h4 class="py-3 border-bottom">New Profile</h4>
    <%= render 'form', profile: @profile %> <%= link_to 'Back', profiles_path %>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
    <aside class="col-12 col-md-3">
      <%= side_panel_on %>
    </aside>
    <div class="col-12 col-md-9 border align-content-center">
      <div class="row my-2">
        <div class="col-lg-9 order-lg-2">
          <ul class="nav nav-tabs">
            <li class="nav-item">
              <a href="" data-target="#profile" data-toggle="tab" class="nav-link active">Profile</a>
            </li>
            <li class="nav-item">
              <a href="" data-target="#messages" data-toggle="tab" class="nav-link">Work Experience</a>
            </li>
            <li class="nav-item">
              <a href="" data-target="#edit" data-toggle="tab" class="nav-link">contact</a>
            </li>
          </ul>
          <div class="tab-content py-4">
            <div class="tab-pane active" id="profile">
              <h5 class="mb-3">User Profile</h5>
              <div class="row">
                <div class="col-md-10">
                  <h6>Personal Statement</h6>
                  <p>
                    <%= @profile.personal_statement %>
                  </p>
                  <h6>Academic Profile</h6>
                  <p>
                    <strong>School:</strong> <%= @profile.school %> <br />
                    <strong>Highest Qualification:</strong> <%= @profile.highest_qualification %>
                  </p>
                </div>
              </div>
              <!--/row-->
            </div>
            <div class="tab-pane" id="messages">
              <div class="alert alert-info alert-dismissable">
                <a class="panel-close close" data-dismiss="alert">×</a>
                <p>
                  <strong>Institution:</strong>
                  <%= @profile.institution %>
                </p>
                <p>
                  <strong>Job Title:</strong>
                  <%= @profile.job_title %>
                </p>
                <p>
                  <strong>Start Date:</strong>
                  <%= @profile.start_date %>
                </p>
                <p>
                  <strong>End Date:</strong>
                  <%= @profile.end_date %>
                </p>
                <p>
                  <strong>Reference Name:</strong>
                  <%= @profile.reference_name %>
                </p>
                <p>
                  <strong>Reference Email:</strong>
                  <%= @profile.reference_email %>
                </p>
                <p>
                  <strong>Gender:</strong>
                  <%= @profile.gender %>
                </p>

                <p>
                  <strong>Date of birth:</strong>
                  <%= @profile.date_of_birth %>
                </p>

                <p>
                  <strong>Designation:</strong>
                  <%= @profile.designation %>
                </p>
              </div>
            </div>
            <div class="tab-pane" id="edit">
              <p>
                <strong>Email address:</strong>
                <%= @profile.email_address %>
              </p>

              <p>
                <strong>Phone number:</strong>
                <%= @profile.phone_number %>
              </p>
              <p>
                <strong>Download CV:</strong>
                <%= image_tag @profile.cv_upload, class: "rounded-circle d-block", width: "70px", height: "70px" %>
              </p>
            </div>
          </div>
        </div>
        <div class="col-lg-3 order-lg-1 text-center">
          <p>
            <% if @profile.picture.attached? %> <%= image_tag @profile.picture, class: "rounded-circle d-block", width: "70px", height: "70px" %> <% else %>
            <img src="//placehold.it/150" class="mx-auto img-fluid rounded-circle d-block" alt="avatar" />
            <% end %>
          </p>
          <h6 class="mt-2">Name: <%= @profile.first_name + " " + @profile.last_name %></h6>
          <h6 class="mt-2">Nationality: <%= @profile.nationality %></h6>
          <h6 class="mt-2">Location: <%= @profile.nationality %></h6>
          <%= link_to 'Edit', edit_profile_path(@profile) %> | <%= link_to 'Back', profiles_path %>
        </div>
      </div>
    </div>
  </div>
</div>