config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'relationships/create'
  get 'relationships/destroy'
  get 'likes/create'
  get 'likes/destroy'
  get 'replies/new'
  get 'replies/create'
  get 'replies/destroy'
  get 'users/index'
  get 'users/show'
  get 'main/home'
  get 'main/about'
  get 'main/contact'
  get 'main/terms'
  get 'main/privacy'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
    resources :replies, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i[create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'profiles#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached:picture
  has_many :posts
  validates :email, uniqueness: true
  validates :username, presence: true, uniqueness: {case_sensitive: false}
  validates_format_of :username, with: /^[a-zA-Z0-9_.]*$/, multiline: true

  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: 'followed_id',
                                   class_name: 'Relationship',
                                   dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  def following?(other_user)
    relationships.find_by_followed_id(other_user)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    #.includes(%i[replies posts likes followed_users followers])
    # @followed_and_user = current_user.followed_users
  end

  def new

  end

  def edit; end

  # PATCH/PUT /usersS/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path, notice: 'User Profile was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order('created_at DESC')
  end

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        current_user == user
      end
    
      def not_followed(user)
        User.where.not(follower_id: user)
      end
    
      def follow_unfollow
        return if current_user?(@user)
    
        if current_user.following?(@user)
          render 'unfollow'
        else
          render 'follow'
        end
      end
    
      def user_feed
        if current_user.following?(@user) || current_user == @user
          if @user.posts.empty?
            raw("<p class='box'>This user does not have posts.</p>")
          else
            render 'feed'
          end
        else
          raw("<p class='box'>Follow this user to see his/her posts.</p>")
        end
      end
end

app/views/users/_profile.html.erb
<div class="wtf-panel py-5">
    <nav class="">
        <article class="">
            <div class="media-content ">
                <figure class=" thumb">
                    <img class="rounded-circle" src="https://louisem.com/wp-content/uploads/2017/07/facebook-link-thumbnail-2017.jpg" height="100px" width="100px">
                </figure>
                <p><%= @user.firstname  %></p>
                <p><small>@<%= @user.username  %></small></p>
            </div>
            <div class="d-flex">
                <div class="stat">
                    <p class="has-text-centered	 "><%= @user.posts.count  %></p>
                    <p class="heading">Posts</p>
                </div>
                <div class="stat">
                 <p class=" has-text-centered	"><%= @user.followed_users.count  %></p>
                    <p class="heading">Following</p>
                   
                </div>
                <div class="stat">
                    <p class="has-text-centered	"><%= @user.followers.count  %></p>
                    <p class="heading">Followers</p>
                </div>
            </div>

            <div class="followed mt-2">
                Followed by:<br>
                <% @user.followers.each do |user| %>
                <br>
                 <div class="is-flex">
                <figure class="image is-32x32 thumb">
                    <img class="rounded-circle" src="https://louisem.com/wp-content/uploads/2017/07/facebook-link-thumbnail-2017.jpg" height="32px" width="32px">
                </figure>
                <div class="ml-2 lef">
                    <p class="fullname"> <%= link_to user.username, user_path(user) %><br>
                    </p>
                    <p class="greyy">@<%= link_to user.username, user_path(user) %><br>
                    </p>
                </div>
                </div>
            </div>
                <%end %>
            </div>
        </article>
    </nav>
</div>

app/views/users/_side_panel.html.erb
<div class="column px-0">
    <nav class="panel pl-3">
        <div class="prof-pic">
            <figure class=" thumb">
                <img class="rounded-circle" src="https://louisem.com/wp-content/uploads/2017/07/facebook-link-thumbnail-2017.jpg" height="100px" width="100px">
            </figure>
            <%= current_user.firstname + "`s " %><%= link_to 'Profile', user_path(current_user), class: "navbar-item" %>  
        </div>
        <div class="d-flex">
            <div class="panel-block mr-1 text-center">
                <div>
                    <p class="heading">Following</p>
                    <p class="panel-block"><%= current_user.followed_users.count  %></p>
                </div>
            </div>
            <div class="panel-block text-center">
                <div>
                    <p class="heading">Followers</p>
                    <p class="panel-block"><%= current_user.followers.count  %></p>
                </div>
            </div>
        </div>
    </nav>
<div class="side-links">
    <ul class="nav flex-column">
        <li class="nav-item">
            <%= link_to 'HOME', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'CONNECT', users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Edit Profile', profiles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Edit Login Details', user_path(current_user), class: "nav-link" %>
        </li>
    </ul>
</div>

app/views/users/edit.html.erb
<%= render 'profile', user: @user %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <aside class="col-12 col-md-3">
      <%= side_panel_on %>
    </aside>
    <section class="col-12 col-md-9">
      <h3>Find your LSA</h3>
      <div class="">
        <% @users.each do |user| %>
        <article class="d-flex">
          <div class="thumbnail">
            <figure class="">
              <img class="rounded-circle" src="https://louisem.com/wp-content/uploads/2017/07/facebook-link-thumbnail-2017.jpg" height="32px" width="32px" />
            </figure>
          </div>
          <div class="ml-2">
            <h4 class="bg-secondary rounded">Learning Support Assistant</h4>
            <div class="">
              Name: <%= link_to user.fullname, user_path(user), class: 'username' %>
            </div>
            <div class="">
              Nationality: <%= user.nationality %>
            </div>
            <div class="">
              Gender: <%= user.gender %>
            </div>
            <div class="">
              <h5>Personal Statement</h5>
              <p>
                It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distributio
              </p>
            </div>
            <div class="">
              <%= link_to user.username, user_path(user), class: 'username' %> <%= link_to user.username, user_path(user), class: 'username' %> <%= link_to user.username, user_path(user), class: 'username' %>
            </div>
          </div>
        </article>
        <% end %>
        <div>
          <section></section>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-4">
            <section class="users-section">
                <%= link_to 'Edit Login Details', edit_user_registration_url, class: "bg-primary py-2 px-2 rounded mx-2 text-dark" %>
                <article class="timeline">
                    <ul class="posts">
                        <h3 class="box title mb-0 no-border">All Post</h3>
                        <ul class="posts">
                        </ul>
                </article>
            </section>
        </div>
    </div>
</div>