config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'relationships/create'
  get 'relationships/destroy'
  get 'likes/create'
  get 'likes/destroy'
  get 'replies/new'
  get 'replies/create'
  get 'replies/destroy'
  get 'users/index'
  get 'users/show'
  get 'main/home'
  get 'main/about'
  get 'main/contact'
  get 'main/terms'
  get 'main/privacy'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
    resources :replies, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i[create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'profiles#index'
end

app/models/post.rb
class Post < ApplicationRecord
  validates :postcontent, presence: true, length: { maximum: 500,
                                                    too_long: '500 characters in post is the maximum allowed.' }
  belongs_to :user, foreign_key: :user_id
  has_many :replies, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  def index
    @likes = Like.all
    @posts = Post.all.order('created_at DESC').includes(%i[user replies])
    @users = User.order('created_at DESC').includes(%i[followed_users followers replies posts])
    return unless current_user

    @post = current_user.posts.new
    @not_followed = User.all.order('created_at DESC') - current_user.followed_users
    @not_followed.delete(current_user)

    ids = current_user.followed_users.ids
    ids << current_user.id
    @followed_and_user_posts = @posts.where(user_id: ids)
  end

  # GET /posts/1
  def show
    @likes = Like.all
    @users = User.all
    @posts = Post.all.order('created_at DESC')
    return unless current_user

    @post = current_user.posts.new
    @not_followed = User.all.order('created_at DESC') - current_user.followed_users
    @not_followed.delete(current_user)
    @followed_and_user_posts = @posts.where(user_id: current_user.followed_users.pluck(:id))
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  
  def create
    @post = current_user.posts.build(post_params)
    # @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }

      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
 
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:postcontent)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def custom_timeline
        friends = current_user.followed_users
        friends_posts = []
        if friends.empty?
          friends_posts = current_user.posts
        else
          friends.each do |friend|
            user_finder = User.find(friend.id)
            friends_posts = user_finder.posts + current_user.posts
          end
        end
        friends
    end
    
      def edit_delete_own_post
        return unless current_user?(@post.user)
    
        link_to edit_post_path(@post), class: 'level-item' do
          raw("  <span class='icon'>
                <i class='fa fa-pencil' aria-hidden='true'></i>
            </span>")
        end
    
        link_to @post, method: :delete, data: { confirm: 'Are you sure you want to delete this post?' },
                        class: 'level-item' do
          raw("  <span class='icon'>
                <i class='fa fa-trash-o' aria-hidden='true'></i>
            </span>")
        end
      end
    
      def delete_own_post(post)
        return unless current_user == post.user
    
        link_to post, method: :delete, data: { confirm: 'Are you sure you want to delete this post?' },
                       class: 'level-item delet' do
          raw("<span class='icon'>
                <i class='fa fa-trash-o'  aria-hidden='true'></i>
            </span>")
        end
      end
end

app/views/posts/_form.html.erb
<%=  simple_form_for(@post) do |f| %>
<%= f.error_notification %>
  <div class="card mt-2">
    <div class="card-header mb-2">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link active"  href="#posts">Make a Post</a>
            </li>
        </ul>
    </div>
    <div class="card-body">
      <div class="form-group">
        <%= f.input :postcontent, label: "And watch someone read", input_html: { class: "input mb-n4"}, wrapper: false, 
        label_html: {class: "ml-2 label"}, placeholder: "Write a Post...", autofocus: true %>
      </div>
    </div>
    <div class="mb-2">
      <%= f.button :submit, class: "float-none float-md-right w-25 mr-md-3 bg-info" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<% @followed_and_user_posts.each do |post| %>
      <div class="my-2 border">
      <article class="media row">
          <div class="col-12 col-md-1">
              <figure class="image is-64x64">
                <img class="rounded-circle" src="https://louisem.com/wp-content/uploads/2017/07/facebook-link-thumbnail-2017.jpg" height="32px" width="32px">
              </figure>
          </div>
          <div class="media-content col-12 col-md-11">
              <div class="content mb-0">
                  <div class="fullname">
                    <span><%= link_to post.user.fullname, user_path(post.user), class: 'fullname' %></span>
                    <p><small>@<%= link_to post.user.username, user_path(post.user), class: 'post-author' %></small></p>
                        <div class="border like">
                            <p><%= post.postcontent %> </p>
                            <div class="feedcount d-md-flex my-2">
                                <div class="flex-fill bg-secondary rounded mx-1">
                                    <span><%= post.likes.count %></span>
                                    <span><%= like_or_dislike_btn(post) %>Likes</span>
                                </div>
                                <div class="flex-fill bg-secondary rounded mr-1">
                                    <span><%= post.likes.count %></span>
                                    <span><%= like_or_dislike_btn(post) %>Comments</span>
                                </div>
                                <div class="flex-fill bg-secondary rounded mr-1">
                                    <span><%= post.likes.count %></span>
                                    <span><%= like_or_dislike_btn(post) %>Shares</span>
                                </div>
                            </div>
                        </div>
                  </div>
                  <div class="d-flex">
                      <div class="mt-3">
                        <%= link_to edit_post_path(post), class: 'level-item edit' do %>
                          <span class="icon">
                              <i class="fa fa-pencil" aria-hidden="true"></i>
                          </span>
                        <% end %>
                        <%= delete_own_post(post) %>
                      </div>
                    </div>
                </div>
              <nav class="block">
                  <div class='comment'>
                      <div class="pl-2">
                        <div class="border rounded">
                          <%= render partial: 'replies/reply', collection: post.replies %>
                        </div>
                          <%= form_for(post.replies.new, url: post_replies_path(post)) do |form| %>
                          <div class="reply-input"><%= form.text_field :content, label: "Post about it", input_html: { class: "input"},
                                                  wrapper: false, label_html: {class: "label"}, placeholder: "Reply this post.",
                                                  autofocus: true %></div>
                          <div class="mb-2">
                            <%= form.submit 'Share', class: "btn btn-sm float-none float-md-right w-25 mr-md-3 bg-info mb-2" %>
                          </div>
                          <% end %>
                      </div>
                  </div>
              </nav>
          </div>

      </article>
        </div>
      <% end %> 

app/views/posts/_who_to_follow.html.erb
<div class="wtf-panel px-3 py-5">
    <nav class="">
        <p class="wtf-heading pb-4 mb-4">WHO TO FOLLOW</p>

        <% @not_followed.each do |user| %>
        <article class="wtf-item">
            <div class="justify column">
                <div class="is-flex">
                    <figure class="image is-32x32 thumb">
                        
                    </figure>
                    <div class="ml-2">
                        <p class="fullname"> <%= link_to user.fullname, user_path(user) %><br>
                        </p>
                    </div>
                </div>
            </div>

        </article>
        <%end %>
    </nav>
</div>

app/views/posts/edit.html.erb
<div class="py-2">
     <article class="media box">
         <figure class="media-left">
             <p class="image is-64x64">
                <img src="https://louisem.com/wp-content/uploads/2017/07/facebook-link-thumbnail-2017.jpg" height="64px" width="64px">
             </p>
         </figure>
         <div class="media-content">
             <%= render 'form' %>
         </div>
     </article>
     <%= link_to 'Show', root_path %> |
     <%= link_to 'Back', posts_path %>

 </div>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
      <aside class="col-12 col-lg-3">
        <%= side_panel_on %>
      </aside>
      <article class="col-12 col-lg-6">
        <div class="mb-3">
            <%= render 'form' %>
        </div>
        <div class="mb-3">
            <%= render 'posts/post' %>
        </div>
      </article>
      <article class="col-12 col-lg-3">
        <div class="mb-3">
            <%= render 'who_to_follow' %>
        </div>
      </article>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
      <aside class="col-12 col-lg-3">
        <%= side_panel_on %>
      </aside>
      <article class="col-12 col-lg-6">
        <div class="mb-3">
            <%= render 'form', post: @post %>
        </div>
        <%= link_to 'Back', posts_path %>
      </article>
      <article class="col-12 col-lg-3">
        <div class="mb-3">
            <p>
                Adverts here
            </p>
        </div>
      </article>
    </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="py-2">
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
            </p>
        </figure>
        <div class="content quote-org justify">
            <div>
                <%= link_to @post.user.fullname, user_path(@post.user), class: 'post-author' %><br>
                <small>@<%= link_to @post.user.username, user_path(@post.user), class: 'post-author' %></small><br />

                <p><%= @post.postcontent %></p>
            </div>
            <div class="quote-icon">
               
                <%= edit_delete_own_post %>                               
            </div>
        </div>
</div>

<div class="media-content">

    <nav class="block">
        <div class='post-comments-section pl-4'>
                <%= render partial: 'replies/reply', collection: @post.replies %>

                <%= form_for(@post.replies.new, url: post_replies_path(@post)) do |form| %>
                <div class="reply-input"><%= form.text_field :content, label: "Post about it", input_html: { class: "input"},
                                                  wrapper: false, label_html: {class: "label"}, placeholder: "Reply this post.",
                                                  autofocus: true %></div>
                <%= form.button :submit, class: "button is-info my-2" %>
                <% end %>
               <%= link_to 'Show', @post %> |
          <%= link_to 'Back', posts_path %> </div>

    </nav>
</div>

</article>

</div>