config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'relationships/create'
  get 'relationships/destroy'
  get 'likes/create'
  get 'likes/destroy'
  get 'replies/new'
  get 'replies/create'
  get 'replies/destroy'
  get 'users/index'
  get 'users/show'
  get 'main/home'
  get 'main/about'
  get 'main/contact'
  get 'main/terms'
  get 'main/privacy'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
    resources :replies, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i[create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'profiles#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImproveEd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@600&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="http://localhost:3000/main/home">
            <%# <%= image_tag ("/assets/logo/Improv_logo.png"), class: "img-responsive logo-image"%>
            <img src="https://github.com/happiguru/Improve-ED/blob/active-storage/app/assets/images/logo/Improv_logo.png" class="img-responsive logo-image">
          </a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="nav navbar-nav align-content-center">
            <li class="nav-item">
              <%= link_to 'Home', main_home_path, class: "nav-link mx-1 rounded text-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ILS List', root_path, class: "nav-link mx-1 rounded text-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Post', posts_path, class: "nav-link mx-1 rounded text-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to 'About', main_about_path, class: "nav-link mx-1 rounded text-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Contact', main_contact_path, class: "nav-link mx-1 rounded text-dark" %>
            </li>
          </ul>
          <ul class="nav navbar-nav ml-auto">
            <% if current_user %> <%= link_to 'New Post', new_post_path, class: "nav-item bg-primary py-2 px-2 rounded mx-2 text-dark" %> <%= link_to 'Sign Out', destroy_user_session_path, class: " nav-item bg-danger text-dark py-2 px-2
            rounded", method: :delete %> <% else %> <%= link_to 'Sign In', new_user_session_path, class: "nav-item bg-primary py-2 px-2 rounded mx-2 text-dark" %> <%= link_to 'Sign Up', new_user_registration_path, class: "nav-item bg-danger
            text-dark py-2 px-2 rounded" %> <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div id="root">
        <%= flash_notice %>
        <%= flash_alert %>
          <%= yield %>
    </div>
    <footer class="footer container-fluid mt-5">
        <div class="row">
          <div class="col-md-3 m-b-30">
            <div class="footer-title m-t-5 m-b-20 p-b-8">
              About us
            </div>
            <p class="white-text">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500 text of the printing.
            </p>
          </div>
          <div class="col-md-3 m-b-30">
            <div class="footer-title m-t-5 m-b-20 p-b-8">
              Latest themes
            </div>
            <div class="footer-links">
              <a href="#">
                Appointment
              </a>
              <a href="#">
                Health center
              </a>
              <a href="#">
                Quality
              </a>
              <a href="#">
                Wallstreet
              </a>
            </div>
          </div>
          <div class="col-md-3 m-b-30">
            <div class="footer-title m-t-5 m-b-20 p-b-8">
              Quick Links
            </div>
            <div class="footer-links">
              <a href="#">
                Blog
              </a>
              <a href="#">
                FAQ
              </a>
              <%= link_to 'Terms of use', main_terms_path, class: "" %>
              <%= link_to 'Privacy policy', main_privacy_path, class: "" %>
            </div>
          </div>
          <div class="col-md-3 m-b-30">
            <div class="footer-title m-t-5 m-b-20 p-b-8">
              Support
            </div>
            <div class="footer-links">
              <a href="#">
                Affiliate
              </a>
              <a href="#">
                Login
              </a>
              <a href="#">
                All theme package
              </a>
              <a href="#">
                Support forum
              </a>
            </div>

            <div class="footer-social-links m-t-30">
              <li>
                <a href="#">
                  <i class="fa fa-facebook" aria-hidden="true"></i>
                </a>
                <a href="#">
                  <i class="fa fa-twitter" aria-hidden="true"></i>
                </a>
                <a href="#">
                  <i class="fa fa-linkedin" aria-hidden="true"></i>
                </a>
                <a href="#">
                  <i class="fa fa-youtube" aria-hidden="true"></i>
                </a>
              </li>
            </div>
          </div>
        </div>
    </footer>
    <div class="footer-bottom">
      Copyright © <%= Time.now.year %>, All Rights Reserved
      ImproveEd (Lekunze)
    </div>

    <script src="https://kit.fontawesome.com/cbdf2b0f0e.js" crossorigin="anonymous"></script>
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>